; SPDX-License-Identifier: GPL-3.0-or-later

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 7.1.3
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLSHELL_BEACON_FIRMWARE_VERSION=\"0.1.0\"
